### ISSUE TITLE
update to 2.3.2

### ISSUE THREAD

**Issue by Lvaskz** [flathub/org.audacityteam.Audacity#36]
Hi, there is a new updating 2.3.2. Can you update ?

**Comment by ovari** [comment]
## [Audacity 2.3.2 Released](https://www.audacityteam.org/audacity-2-3-2-released/)

Audacity 2.3.2 replaces all previous versions for Windows, macOS and Linux. 

### Improvements
- Audacity now includes the LAME mp3 encoder. Previously, due to now expired patents, you had to download it separately.
- There is a new ‘Select’ button in the track panel to select the whole track.
- Audacity mod-script-pipe for driving Audacity from Python now comes with Audacity and can be enabled via preferences.
- Options and preferences:
o Type to Create a Label is now off by default.
o A plug-in installer for Nyquist now provides a file browser for
o selecting ‘.NY’ files to install.

See also: https://wiki.audacityteam.org/wiki/New_features_in_Audacity_2.3.2

### Bug Fixes

Over 20 bugs in 2.3.1 fixed, including:
- Audacity 2.3.1 would crash if append-recording to a collapsed track.

See also: https://wiki.audacityteam.org/wiki/Release_Notes_2.3.2

## [Audacity 2.3.1 Released](https://www.audacityteam.org/audacity-2-3-1-released/)

Audacity 2.3.1 replaces all previous versions for Windows, macOS and Linux. We’ve restored support for Linux which was missing in 2.3.0.

**Comment by go-ten** [comment]
Hi,
Any News for This?

**Comment by antistress** [comment]
Hi, my version shows 2.3.2 even if GNOME Software and FlatHub say 2.3.0
 so I think this bug can be closed ?
