### ISSUE TITLE
Audio Plugin support doesn't work

### ISSUE THREAD

**Issue by neildarlow** [flathub/org.audacityteam.Audacity#57]
I have the latest Audacity flatpak update (Oct. 4th 2020) and org.LinuxAudio.Plugins.swh and org.gnome.Platform 3.38 installed.

Under Preferences|Effects I have all plugin types enabled but in Tools Add / Remove Plug-ins... only the bundled effects are listed.

It seems that Audacity doesn't see the plugins.

**Comment by eszlari** [comment]
CC @hfiguiere

**Comment by hfiguiere** [comment]
I just tested with swh plugins and they appear. Do you have the proper flatpak ? I need `org.freedesktop.LinuxAudio.Plugins.swh//20.08` (and not `//19.08`).

**Comment by neildarlow** [comment]
Hi @hfiguiere,

I didn't have org.freedesktop.LinuxAudio.Plugins.swh/x86_64/20.08. I had to install it manually.

Won't that be a problem? I see you have the **no-autodownload: true** option in the build settings for it.

**Comment by hfiguiere** [comment]
It doesn't install any by default. There are currently 30 plugin packages with varying format.

The extension point defined in the package is for ALL plugins, so it has to be "no-autodownload: true"

**Comment by neildarlow** [comment]
Thank you. I didn't know that.

I've noticed a number of questions on the Audacity Forums in the GNU/Linux section relating to this Flatpak. I'm just thinking how to communicate the need to install a plugins flatpak manually (and the reasoning why it needs to be done) to users who have just installed it and post there asking why plugins don't work. At the moment, the moderators (steve in particular) just have to tell users that the Audacity project has nothing to do with the flatpak.

**Comment by hfiguiere** [comment]
Plugins are not installed automatically because:
1. they are plugins
2. they are not specific to Audacity. Audacity is just the latest flatpak audio app to get the support - you can use the exact same plugins in a number off apps: Ardour, MuseSequencer, LMMS, Hydrogen, gsequencer, Mixxx, Shutcut, Flowblade, etc.
3. They total a few GB.

I know discovery of the plugins in Flatpak isn't great and it's probably one of the next things to be fixed.

One way to do it (at least on Fedora) is to go into the "Software" application, look for "Linux Audio" and there should be a list of plugins.

Albeit with issues, see https://gitlab.gnome.org/GNOME/gnome-software/-/issues/1020

BTW since we are dealing with upstream, I have a patch to *fix* plugin support:
https://github.com/audacity/audacity/pull/590

**Comment by hfiguiere** [comment]
We can close this issue I think.

**Comment by eszlari** [comment]
As long as GNOME Software and Plasma Discover don't handle extensions well, I think we should keep it open.
